
package com.tst.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sun Apr 24 13:02:24 EDT 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getProductsResponse", namespace = "http://ws.tst.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductsResponse", namespace = "http://ws.tst.com/")

public class GetProductsResponse {

    @XmlElement(name = "return")
    private java.util.List<com.tst.ws.model.Product> _return;

    public java.util.List<com.tst.ws.model.Product> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.tst.ws.model.Product> new_return)  {
        this._return = new_return;
    }

}

