
package com.tst.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sun Apr 24 13:02:24 EDT 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getProducts", namespace = "http://ws.tst.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProducts", namespace = "http://ws.tst.com/")

public class GetProducts {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

