<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ProductCatalogService" targetNamespace="http://ws.tst.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.tst.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://ws.tst.com/" schemaLocation="productcatalog_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="getProductDescriptionResponse">
    <wsdl:part name="parameters" element="tns:getProductDescriptionResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getProductDescription">
    <wsdl:part name="parameters" element="tns:getProductDescription">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ProductCatalogSEI">
    <wsdl:operation name="getProductDescription">
      <wsdl:input name="getProductDescription" message="tns:getProductDescription">
    </wsdl:input>
      <wsdl:output name="getProductDescriptionResponse" message="tns:getProductDescriptionResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ProductCatalogServiceSoapBinding" type="tns:ProductCatalogSEI">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getProductDescription">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getProductDescription">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getProductDescriptionResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ProductCatalogService">
    <wsdl:port name="ProductCatalogPort" binding="tns:ProductCatalogServiceSoapBinding">
      <soap:address location="http://localhost:9080/ProductCatalogWS/services"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
